server:
  port: 9000
  servlet:
    session:
      cookie:
        # id/api running localhost so need to change cookie name
        name: IDSESSION

spring:
  application:
    name: idserver
  autoconfigure:
    exclude:
    - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://localhost:8080/login/oauth2/code/oidc-client"
              post-logout-redirect-uris:
                - "http://localhost:8080"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: false
          cc-client:
            registration:
              client-id: "cc-client"
              client-secret: "{noop}secret2"
              client-authentication-methods:
                - "client_secret_post"
              authorization-grant-types:
                - "client_credentials"

logging:
  level:
    org.springframework.security: trace
    com.github.jvalkeal.secpat: trace
